app = 'nibras-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile.api'

[http_service]
  internal_port = 4848
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.health]
    grace_period = "10s"
    interval = "15s"
    method = "GET"
    path = "/healthz"
    port = 4848
    timeout = "5s"
    type = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
